<?php
/**
 * Local development setup helpers. Used by install-*.sh scripts to:
 * - Auto-detect available databases (SQLite, MySQL)
 * - Generate config/config.php with sensible dev defaults
 * - Create/reset schema
 * - Seed dummy data for testing
 *
 * This is dev-only setup, never called by production code.
 */

declare(strict_types=1);

/**
 * Auto-detect available database: MySQL (if running) or SQLite (fallback).
 * Prints error and exits if neither available.
 */
function dev_detect_database(): array {
    // Try MySQL on localhost
    $mysqlRunning = false;
    $mysqlError = '';
    try {
        $pdo = new PDO(
            'mysql:host=127.0.0.1;port=3306',
            'root',
            '',
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        $mysqlRunning = true;
    } catch (PDOException $e) {
        $mysqlError = $e->getMessage();
    }

    if ($mysqlRunning) {
        echo "[✓] MySQL detected at localhost:3306\n";
        return ['driver' => 'mysql', 'host' => '127.0.0.1', 'port' => 3306];
    }

    // Fall back to SQLite
    $sqlitePath = __DIR__ . '/../../storage/gallery.sqlite';
    echo "[✓] Using SQLite at $sqlitePath\n";
    return ['driver' => 'sqlite', 'path' => $sqlitePath];
}

/**
 * Generate config/config.php with dev defaults and auto-detected database.
 */
function dev_generate_config(array $dbConfig): array {
    $randomPassword = bin2hex(random_bytes(8));
    $hmacKey = bin2hex(random_bytes(32));
    $cronSecret = bin2hex(random_bytes(16));

    $config = [
        'dev_mode' => 'local',

        'db' => $dbConfig['driver'] === 'mysql'
            ? [
                'driver'  => 'mysql',
                'host'    => $dbConfig['host'] ?? '127.0.0.1',
                'port'    => $dbConfig['port'] ?? 3306,
                'name'    => 'gallery_dev',
                'user'    => 'root',
                'pass'    => '',
                'charset' => 'utf8mb4',
            ]
            : [
                'driver' => 'sqlite',
                'path'   => $dbConfig['path'],
            ],

        'site' => [
            'name'          => 'Local Test Gallery',
            'base_url'      => 'http://localhost:8000',
            'support_email' => 'admin@localhost',
        ],

        'currency' => 'GBP',

        'branding' => [
            'theme' => 'podium-ink',
        ],

        'stripe' => [
            'publishable_key' => 'pk_test_local',
            'secret_key'      => 'sk_test_local',
            'webhook_secret'  => 'whsec_test_local',
        ],

        'smtp' => [
            'host'       => '',
            'port'       => 587,
            'user'       => '',
            'pass'       => '',
            'from_email' => 'noreply@localhost',
            'from_name'  => 'Local Test Gallery',
        ],

        'discounts' => [
            10 => 0.15,
            20 => 0.20,
            50 => 0.25,
        ],

        'security' => [
            'hmac_key' => $hmacKey,
            'cron_secret' => $cronSecret,
        ],

        'timezone' => 'UTC',
        'storage_mode' => 'local',
        'admin_mode' => 'local',
    ];

    return ['config' => $config, 'adminPassword' => $randomPassword];
}

/**
 * Write config array to config/config.php.
 */
function dev_write_config(array $config): string {
    $configPath = __DIR__ . '/../../config/config.php';
    $php = "<?php\n// Auto-generated by local dev installer\n// DO NOT COMMIT THIS FILE - it contains credentials\nreturn " . var_export($config, true) . ";\n";

    if (!file_put_contents($configPath, $php)) {
        fwrite(STDERR, "[✗] Failed to write config/config.php\n");
        exit(1);
    }

    return $configPath;
}

/**
 * Connect to database using config.
 */
function dev_connect_db(array $config): PDO {
    $dbConfig = $config['db'];

    try {
        if ($dbConfig['driver'] === 'sqlite') {
            @mkdir(dirname($dbConfig['path']), 0755, true);
            $pdo = new PDO(
                'sqlite:' . $dbConfig['path'],
                null,
                null,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );
        } else {
            // MySQL
            $pdo = new PDO(
                sprintf(
                    'mysql:host=%s;port=%d',
                    $dbConfig['host'],
                    $dbConfig['port']
                ),
                $dbConfig['user'],
                $dbConfig['pass'],
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );
            // Create/select database
            $pdo->exec('CREATE DATABASE IF NOT EXISTS ' . $dbConfig['name']);
            $pdo->exec('USE ' . $dbConfig['name']);
        }

        return $pdo;
    } catch (PDOException $e) {
        fwrite(STDERR, "[✗] Database connection failed: " . $e->getMessage() . "\n");
        exit(1);
    }
}

/**
 * Drop all tables and re-run migrations from scratch.
 */
function dev_reset_schema(PDO $pdo): void {
    echo "[*] Resetting database schema...\n";
    try {
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'sqlite') {
            $tables = $pdo->query("SELECT name FROM sqlite_master WHERE type='table'")->fetchAll(PDO::FETCH_COLUMN);
            foreach ($tables as $table) {
                if ($table !== 'sqlite_sequence') {
                    $pdo->exec("DROP TABLE IF EXISTS " . $table);
                }
            }
        } else {
            $pdo->exec('SET FOREIGN_KEY_CHECKS = 0');
            $tables = $pdo->query("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE()")->fetchAll(PDO::FETCH_COLUMN);
            foreach ($tables as $table) {
                $pdo->exec("DROP TABLE " . $table);
            }
            $pdo->exec('SET FOREIGN_KEY_CHECKS = 1');
        }

        require_once __DIR__ . '/migrations.php';
        $migrationsDir = __DIR__ . '/../../migrations';
        $initial001 = $driver === 'sqlite' ? '001_initial_schema.sqlite.sql' : '001_initial_schema.sql';

        try {
            migrations_apply($pdo, $migrationsDir, $initial001);
        } catch (PDOException $e) {
            if (strpos($e->getMessage(), 'UNIQUE constraint failed') === false && strpos($e->getMessage(), 'Duplicate entry') === false) {
                throw $e;
            }
        }

        // Apply remaining migrations (002+)
        // migrations_pending() already handles driver-specific variants
        $pending = migrations_pending($pdo, $migrationsDir);
        foreach ($pending as $filename) {
            migrations_apply($pdo, $migrationsDir, $filename);
        }
        echo "[✓] Schema created\n";
    } catch (Exception $e) {
        fwrite(STDERR, "[✗] Schema reset failed: " . $e->getMessage() . "\n");
        exit(1);
    }
}

/**
 * Seed randomized dummy data for local dev: several events with rosters,
 * sessions, photos/videos, orders, view stats, and cohort rows — enough
 * that every admin view (dashboard, analytics, reporting, orders, events)
 * has something real to render instead of an empty state. Numbers and
 * names are randomized per run rather than fixed, so repeated local
 * installs don't all look identical.
 */
function dev_seed_dummy_data(PDO $pdo): void {
    echo "[*] Seeding dummy data...\n";

    try {
        $eventDefs = [
            ['Silverstone Sprint Cup', 'Silverstone Circuit', 45, 500],
            ['Brands Hatch Club Day', 'Brands Hatch', 30, 600],
            ['Donington Park Trophy', 'Donington Park', 14, 450],
            ['Oulton Park Endurance', 'Oulton Park', 2, 750],
        ];
        $classes = ['Cadet', 'Junior Rotax', 'Senior Rotax', 'IAME X30'];
        $sessionNames = ['Qualifying', 'Heat 1', 'Heat 2', 'Final'];
        $firstNames = ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Henry', 'Isla', 'Jack', 'Kate', 'Liam', 'Mia', 'Noah', 'Olivia'];
        $lastNames = ['Smith', 'Jones', 'Taylor', 'Brown', 'Wilson', 'Evans', 'Walker', 'Wright', 'Green', 'Hall'];

        $eventPrices = [];       // event_id => price_single_pence
        $eventPhotoIds = [];     // event_id => [photo_id, ...] (photos only, not videos)

        foreach ($eventDefs as [$title, $venue, $daysAgo, $priceSingle]) {
            $eventDate = date('Y-m-d', strtotime("-{$daysAgo} days"));
            $slug = strtolower(str_replace(' ', '-', $title)) . '-' . date('Y', strtotime($eventDate));

            $stmt = $pdo->prepare(
                'INSERT INTO events (title, slug, venue, event_date, is_published, price_single_pence, price_session_pence, price_event_pence)
                 VALUES (?, ?, ?, ?, 1, ?, ?, ?)'
            );
            $stmt->execute([$title, $slug, $venue, $eventDate, $priceSingle, $priceSingle * 4, $priceSingle * 8]);
            $eventId = (int)$pdo->lastInsertId();
            $eventPrices[$eventId] = $priceSingle;

            // Race entry roster (kart/driver/class): backs both the filter
            // dropdowns (fetched from event_entries) and the tags on photos
            // below (so a filter someone picks actually matches something).
            $roster = [];
            for ($r = 0, $entryCount = random_int(8, 14); $r < $entryCount; $r++) {
                $entry = [
                    'kart' => (string)random_int(1, 99),
                    'driver' => $firstNames[array_rand($firstNames)] . ' ' . $lastNames[array_rand($lastNames)],
                    'class' => $classes[array_rand($classes)],
                ];
                $roster[] = $entry;
                try {
                    $pdo->prepare('INSERT INTO event_entries (event_id, kart_number, driver_name, class) VALUES (?, ?, ?, ?)')
                        ->execute([$eventId, $entry['kart'], $entry['driver'], $entry['class']]);
                } catch (PDOException $e) {
                    // Random kart+class combo collided with an earlier one for
                    // this event (unique constraint) — harmless, skip it.
                }
            }

            // 1-3 sessions per event
            $sessionIds = [];
            for ($s = 0, $numSessions = random_int(1, 3); $s < $numSessions; $s++) {
                $name = $sessionNames[$s] ?? ('Session ' . ($s + 1));
                $stmt = $pdo->prepare('INSERT INTO sessions (event_id, name, slug, sort_order) VALUES (?, ?, ?, ?)');
                $stmt->execute([$eventId, $name, strtolower(str_replace(' ', '-', $name)), $s + 1]);
                $sessionIds[] = (int)$pdo->lastInsertId();
            }

            // Photos (and a few videos) scattered across sessions, each
            // tagged from the roster above.
            $photoIds = [];
            for ($p = 0, $photoCount = random_int(20, 40); $p < $photoCount; $p++) {
                $sessionId = $sessionIds[array_rand($sessionIds)];
                $isVideo = random_int(1, 20) === 1; // ~5% video
                $mediaType = $isVideo ? 'video' : 'photo';
                $token = substr(bin2hex(random_bytes(6)), 0, 12);
                $filename = ($isVideo ? 'clip-' : 'photo-') . ($p + 1) . ($isVideo ? '.mp4' : '.jpg');

                $stmt = $pdo->prepare(
                    "INSERT INTO photos (event_id, session_id, public_token, original_filename, media_type, width, height, hires_size_bytes, status, view_count, sort_order)
                     VALUES (?, ?, ?, ?, ?, 1920, 1080, ?, 'live', ?, ?)"
                );
                $stmt->execute([$eventId, $sessionId, $token, $filename, $mediaType, random_int(1_500_000, 6_500_000), random_int(0, 120), $p]);
                $photoId = (int)$pdo->lastInsertId();

                $entry = $roster[array_rand($roster)];
                $pdo->prepare('INSERT INTO photo_tags (photo_id, kart_number, driver_name, class) VALUES (?, ?, ?, ?)')
                    ->execute([$photoId, $entry['kart'], $entry['driver'], $entry['class']]);

                if (!$isVideo) {
                    $photoIds[] = $photoId;
                }
            }
            $eventPhotoIds[$eventId] = $photoIds;

            // Three weeks of view history so the analytics trend chart has
            // something to plot rather than a flat line.
            for ($d = 0; $d < 21; $d++) {
                $date = date('Y-m-d', strtotime("-{$d} days"));
                $pdo->prepare('INSERT INTO stats_daily (stat_date, event_id, gallery_views, photo_views) VALUES (?, ?, ?, ?)')
                    ->execute([$date, $eventId, random_int(5, 80), random_int(20, 400)]);
            }
        }

        // Orders spread across events/customers/dates, mostly paid with a
        // realistic mix of pending and refunded, so the orders list,
        // dashboard revenue card, and reporting cohorts aren't all zero.
        $eventIds = array_keys($eventPhotoIds);
        $statusPool = ['paid', 'paid', 'paid', 'paid', 'paid', 'paid', 'pending', 'pending', 'refunded'];
        for ($o = 0, $orderCount = random_int(25, 35); $o < $orderCount; $o++) {
            $eventId = $eventIds[array_rand($eventIds)];
            $photoPool = $eventPhotoIds[$eventId];
            if (empty($photoPool)) {
                continue;
            }

            shuffle($photoPool);
            $chosen = array_slice($photoPool, 0, min(random_int(1, 4), count($photoPool)));
            $unitPrice = $eventPrices[$eventId];

            $status = $statusPool[array_rand($statusPool)];
            $createdAt = date('Y-m-d H:i:s', strtotime('-' . random_int(0, 45) . ' days'));
            $paidAt = in_array($status, ['paid', 'refunded'], true) ? $createdAt : null;
            $refundedAt = $status === 'refunded' ? date('Y-m-d H:i:s', strtotime($createdAt . ' +2 days')) : null;

            $stmt = $pdo->prepare(
                "INSERT INTO orders (public_token, email, status, currency, total_pence, paid_at, refunded_at, created_at)
                 VALUES (?, ?, ?, 'GBP', ?, ?, ?, ?)"
            );
            $email = strtolower($firstNames[array_rand($firstNames)] . '.' . $lastNames[array_rand($lastNames)]) . '@example.com';
            $stmt->execute([bin2hex(random_bytes(11)), $email, $status, $unitPrice * count($chosen), $paidAt, $refundedAt, $createdAt]);
            $orderId = (int)$pdo->lastInsertId();

            foreach ($chosen as $photoId) {
                $pdo->prepare(
                    "INSERT INTO order_items (order_id, item_type, photo_id, event_id, description, unit_price_pence, quantity, line_total_pence)
                     VALUES (?, 'photo', ?, ?, ?, ?, 1, ?)"
                )->execute([$orderId, $photoId, $eventId, "Photo #{$photoId}", $unitPrice, $unitPrice]);
            }
        }

        // Derive customer_analytics from the orders just created, via the
        // same function the real reporting cron uses — exercises the real
        // code path instead of hand-seeding a parallel copy of its output.
        require_once __DIR__ . '/reporting.php';
        update_customer_analytics($pdo);

        // No cohort-builder exists yet (get_cohort_analysis() only reads),
        // so these rows are hand-seeded rather than derived.
        $anchor = strtotime(date('Y-m-01'));  // anchor to 1st to prevent day-31 overflow
        for ($m = 0; $m < 4; $m++) {
            $month = date('Y-m-01', strtotime("-{$m} months", $anchor));
            $pdo->prepare(
                'INSERT INTO cohorts (cohort_month, customers_acquired, revenue_pence, retention_month_1, retention_month_3, retention_month_6)
                 VALUES (?, ?, ?, ?, ?, ?)'
            )->execute([$month, random_int(5, 20), random_int(15000, 80000), random_int(10, 60), random_int(5, 40), random_int(0, 25)]);
        }

        echo '[✓] Seeded ' . count($eventDefs) . " events with rosters, sessions, photos/videos, orders, and analytics data\n";
    } catch (Exception $e) {
        fwrite(STDERR, "[✗] Data seeding failed: " . $e->getMessage() . "\n");
        exit(1);
    }
}
