<?php
/**
 * Local development setup helpers. Used by install-*.sh scripts to:
 * - Auto-detect available databases (SQLite, MySQL)
 * - Generate config/config.php with sensible dev defaults
 * - Create/reset schema
 * - Seed dummy data for testing
 *
 * This is dev-only setup, never called by production code.
 */

declare(strict_types=1);

/**
 * Auto-detect available database: MySQL (if running) or SQLite (fallback).
 * Prints error and exits if neither available.
 */
function dev_detect_database(): array {
    // Try MySQL on localhost
    $mysqlRunning = false;
    $mysqlError = '';
    try {
        $pdo = new PDO(
            'mysql:host=127.0.0.1;port=3306',
            'root',
            '',
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        $mysqlRunning = true;
    } catch (PDOException $e) {
        $mysqlError = $e->getMessage();
    }

    if ($mysqlRunning) {
        echo "[✓] MySQL detected at localhost:3306\n";
        return ['driver' => 'mysql', 'host' => '127.0.0.1', 'port' => 3306];
    }

    // Fall back to SQLite
    $sqlitePath = __DIR__ . '/../../storage/gallery.sqlite';
    echo "[✓] Using SQLite at $sqlitePath\n";
    return ['driver' => 'sqlite', 'path' => $sqlitePath];
}

/**
 * Generate config/config.php with dev defaults and auto-detected database.
 */
function dev_generate_config(array $dbConfig): array {
    $randomPassword = bin2hex(random_bytes(8));
    $hmacKey = bin2hex(random_bytes(32));
    $cronSecret = bin2hex(random_bytes(16));

    $config = [
        'dev_mode' => 'local',

        'db' => $dbConfig['driver'] === 'mysql'
            ? [
                'driver'  => 'mysql',
                'host'    => $dbConfig['host'] ?? '127.0.0.1',
                'port'    => $dbConfig['port'] ?? 3306,
                'name'    => 'gallery_dev',
                'user'    => 'root',
                'pass'    => '',
                'charset' => 'utf8mb4',
            ]
            : [
                'driver' => 'sqlite',
                'path'   => $dbConfig['path'],
            ],

        'site' => [
            'name'          => 'Local Test Gallery',
            'base_url'      => 'http://localhost:8000',
            'support_email' => 'admin@localhost',
        ],

        'currency' => 'GBP',

        'branding' => [
            'theme' => 'podium-ink',
        ],

        'stripe' => [
            'publishable_key' => 'pk_test_local',
            'secret_key'      => 'sk_test_local',
            'webhook_secret'  => 'whsec_test_local',
        ],

        'smtp' => [
            'host'       => '',
            'port'       => 587,
            'user'       => '',
            'pass'       => '',
            'from_email' => 'noreply@localhost',
            'from_name'  => 'Local Test Gallery',
        ],

        'discounts' => [
            10 => 0.15,
            20 => 0.20,
            50 => 0.25,
        ],

        'security' => [
            'hmac_key' => $hmacKey,
            'cron_secret' => $cronSecret,
        ],

        'timezone' => 'UTC',
        'storage_mode' => 'local',
        'admin_mode' => 'local',
    ];

    return ['config' => $config, 'adminPassword' => $randomPassword];
}

/**
 * Write config array to config/config.php.
 */
function dev_write_config(array $config): string {
    $configPath = __DIR__ . '/../../config/config.php';
    $php = "<?php\n// Auto-generated by local dev installer\n// DO NOT COMMIT THIS FILE - it contains credentials\nreturn " . var_export($config, true) . ";\n";

    if (!file_put_contents($configPath, $php)) {
        fwrite(STDERR, "[✗] Failed to write config/config.php\n");
        exit(1);
    }

    return $configPath;
}

/**
 * Connect to database using config.
 */
function dev_connect_db(array $config): PDO {
    $dbConfig = $config['db'];

    try {
        if ($dbConfig['driver'] === 'sqlite') {
            @mkdir(dirname($dbConfig['path']), 0755, true);
            $pdo = new PDO(
                'sqlite:' . $dbConfig['path'],
                null,
                null,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );
        } else {
            // MySQL
            $pdo = new PDO(
                sprintf(
                    'mysql:host=%s;port=%d',
                    $dbConfig['host'],
                    $dbConfig['port']
                ),
                $dbConfig['user'],
                $dbConfig['pass'],
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );
            // Create/select database
            $pdo->exec('CREATE DATABASE IF NOT EXISTS ' . $dbConfig['name']);
            $pdo->exec('USE ' . $dbConfig['name']);
        }

        return $pdo;
    } catch (PDOException $e) {
        fwrite(STDERR, "[✗] Database connection failed: " . $e->getMessage() . "\n");
        exit(1);
    }
}

/**
 * Drop all tables and re-run migrations from scratch.
 */
function dev_reset_schema(PDO $pdo): void {
    echo "[*] Resetting database schema...\n";
    try {
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'sqlite') {
            $tables = $pdo->query("SELECT name FROM sqlite_master WHERE type='table'")->fetchAll(PDO::FETCH_COLUMN);
            foreach ($tables as $table) {
                if ($table !== 'sqlite_sequence') {
                    $pdo->exec("DROP TABLE IF EXISTS " . $table);
                }
            }
        } else {
            $pdo->exec('SET FOREIGN_KEY_CHECKS = 0');
            $tables = $pdo->query("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE()")->fetchAll(PDO::FETCH_COLUMN);
            foreach ($tables as $table) {
                $pdo->exec("DROP TABLE " . $table);
            }
            $pdo->exec('SET FOREIGN_KEY_CHECKS = 1');
        }

        require_once __DIR__ . '/migrations.php';
        $migrationsDir = __DIR__ . '/../../migrations';
        $initial001 = $driver === 'sqlite' ? '001_initial_schema.sqlite.sql' : '001_initial_schema.sql';

        try {
            migrations_apply($pdo, $migrationsDir, $initial001);
        } catch (PDOException $e) {
            if (strpos($e->getMessage(), 'UNIQUE constraint failed') === false && strpos($e->getMessage(), 'Duplicate entry') === false) {
                throw $e;
            }
        }

        // Apply remaining migrations (002+)
        // migrations_pending() already handles driver-specific variants
        $pending = migrations_pending($pdo, $migrationsDir);
        foreach ($pending as $filename) {
            migrations_apply($pdo, $migrationsDir, $filename);
        }
        echo "[✓] Schema created\n";
    } catch (Exception $e) {
        fwrite(STDERR, "[✗] Schema reset failed: " . $e->getMessage() . "\n");
        exit(1);
    }
}

/**
 * Seed dummy data: one event, 10 photos per session, dummy tags.
 */
function dev_seed_dummy_data(PDO $pdo): void {
    echo "[*] Seeding dummy data...\n";

    try {
        // Create event
        $stmt = $pdo->prepare(
            'INSERT INTO events (title, slug, event_date, is_published, price_single_pence, price_session_pence, price_event_pence)
             VALUES (?, ?, ?, 1, 500, 2500, 5000)'
        );
        $stmt->execute(['Test Event', 'test-event', date('Y-m-d')]);
        $eventId = (int)$pdo->lastInsertId();

        // Create session
        $stmt = $pdo->prepare(
            'INSERT INTO sessions (event_id, name, slug, sort_order)
             VALUES (?, ?, ?, 1)'
        );
        $stmt->execute([$eventId, 'Test Session', 'test-session']);
        $sessionId = (int)$pdo->lastInsertId();

        // Create 10 photos
        for ($i = 1; $i <= 10; $i++) {
            $stmt = $pdo->prepare(
                'INSERT INTO photos (event_id, session_id, public_token, original_filename, width, height, hires_size_bytes, status, view_count)
                 VALUES (?, ?, ?, ?, 1920, 1080, 2048000, \'live\', 0)'
            );
            $token = substr(bin2hex(random_bytes(6)), 0, 12);
            $stmt->execute([$eventId, $sessionId, $token, "test-photo-$i.jpg"]);
            $photoId = (int)$pdo->lastInsertId();

            // Add kart metadata to photos
            $kartNumber = 100 + $i;
            $drivers = ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'];
            $driver = $drivers[$i % count($drivers)];
            $stmt = $pdo->prepare('INSERT INTO photo_tags (photo_id, kart_number, driver_name) VALUES (?, ?, ?)');
            $stmt->execute([$photoId, (string)$kartNumber, $driver]);
        }

        echo "[✓] Seeded 1 event, 1 session, 10 photos with tags\n";
    } catch (Exception $e) {
        fwrite(STDERR, "[✗] Data seeding failed: " . $e->getMessage() . "\n");
        exit(1);
    }
}
